# Generated by Django 2.2.8 on 2020-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='link',
            name='TypeOfEvent',
            field=models.CharField(choices=[('1', 'Material'), ('2', 'Quiz')], default='1', max_length=20),
        ),
    ]
